"use client";

import { useMemo, useState } from "react";
import { demoBenefits, demoHoldings, eligibleBenefits, totalSavings } from "../lib/portfolio";

export default function Home() {
  const [destination, setDestination] = useState("Tokyo, Japan");
  const [searched, setSearched] = useState(false);
  const eligible = useMemo(() => eligibleBenefits(demoHoldings, demoBenefits), []);
  const savings = totalSavings(eligible);

  return (
    <main className="min-h-screen bg-[#f7f7f4] text-[#151515]">
      <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><a href="/" className="text-xl font-semibold tracking-tight">ShareNomad<span className="text-[#777]">.</span></a><div className="hidden gap-8 text-sm text-[#666] md:flex"><a href="/portfolio">Portfolio</a><a href="#benefits">Explore</a><a href="#trip">Trips</a></div><a href="/portfolio" className="rounded-full border border-[#ddd] bg-white px-4 py-2 text-sm">Manage holdings</a></nav>
      <section className="mx-auto max-w-6xl px-6 pb-10 pt-12"><div className="max-w-3xl"><p className="mb-4 text-sm font-medium uppercase tracking-[0.2em] text-[#777]">Shareholder lifestyle intelligence</p><h1 className="text-5xl font-semibold leading-[1.05] tracking-[-0.04em] md:text-7xl">Your assets.<br/>Your benefits.<br/><span className="text-[#777]">Your world.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#666]">Turn the companies you own into practical benefits for travel, food, stays and experiences.</p></div></section>
      <section className="mx-auto grid max-w-6xl gap-5 px-6 pb-10 md:grid-cols-3"><Stat label="Portfolio positions" value={`${demoHoldings.length}`} sub="Manual holdings" /><Stat label="Eligible benefits" value={`${eligible.length}`} sub="Current demo catalog" /><Stat label="Potential trip saving" value={`€${savings}`} sub="Tokyo demo" /></section>
      <section id="trip" className="mx-auto max-w-6xl px-6 pb-12"><div className="rounded-[28px] bg-[#171717] p-6 text-white md:p-8"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm text-[#aaa]">Find shareholder benefits</p><h2 className="mt-1 text-3xl font-medium tracking-tight">Where are you going?</h2></div><p className="text-sm text-[#aaa]">Eligibility is checked against demo benefits.</p></div><div className="flex flex-col gap-3 md:flex-row"><input value={destination} onChange={e => setDestination(e.target.value)} className="min-h-14 flex-1 rounded-2xl bg-white px-5 text-base text-black outline-none" placeholder="Tokyo, Japan" /><button onClick={() => setSearched(true)} className="min-h-14 rounded-2xl bg-white px-7 font-medium text-black transition hover:bg-[#eee]">Find my benefits →</button></div>{searched && <p className="mt-4 text-sm text-[#bbb]">Found {eligible.length} eligible demo benefits around {destination}.</p>}</div></section>
      <section className="mx-auto max-w-6xl px-6 pb-20"><div className="mb-5 flex items-end justify-between"><div><p className="text-sm text-[#888]">Portfolio</p><h2 className="text-3xl font-semibold tracking-tight">Holdings</h2></div><a href="/portfolio" className="text-sm font-medium">Add or edit →</a></div><div className="grid gap-3 md:grid-cols-3">{demoHoldings.map(h => <div key={h.ticker} className="rounded-3xl border border-[#e2e2de] bg-white p-5"><div className="flex items-center justify-between"><span className="rounded-xl bg-[#f1f1ed] px-3 py-2 text-sm font-semibold">{h.ticker}</span><span className="text-sm text-[#888]">{h.shares} shares</span></div><p className="mt-5 font-medium">{h.name}</p><p className="mt-1 text-sm text-[#888]">Manual holding</p></div>)}</div></section>
      <section id="benefits" className="border-t border-[#e2e2de] bg-white"><div className="mx-auto max-w-6xl px-6 py-16"><div className="mb-7 flex items-end justify-between"><div><p className="text-sm text-[#888]">Tokyo demo</p><h2 className="text-3xl font-semibold tracking-tight">Benefits you qualify for</h2></div><div className="text-right"><p className="text-sm text-[#888]">Potential saving</p><p className="text-2xl font-semibold">€{savings}</p></div></div><div className="grid gap-4 md:grid-cols-2">{eligible.map(b => <div key={b.id} className="rounded-3xl border border-[#e2e2de] p-5"><div className="flex justify-between gap-4"><div><p className="font-medium">{b.title}</p><p className="mt-1 text-sm text-[#888]">{b.company} · {b.category}</p></div><span className="font-semibold">€{b.saving} save</span></div><div className="mt-5 flex justify-between text-xs text-[#999]"><span>{b.distance} away</span><span>DEMO • source required</span></div></div>)}</div></div></section>
      <footer className="mx-auto max-w-6xl px-6 py-10 text-sm text-[#999]">ShareNomad MVP • Informational only, not investment advice.</footer>
    </main>
  );
}
function Stat({ label, value, sub }: { label: string; value: string; sub: string }) { return <div className="rounded-3xl border border-[#e2e2de] bg-white p-6"><p className="text-sm text-[#888]">{label}</p><p className="mt-4 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-sm text-[#888]">{sub}</p></div>; }
